import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header"; 
import "./globals.css";
import Footer from "@/components/footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        
        
        <Header />
        

        {/* Page content */}
        <main className="flex-1">
          {children}
        </main>
<Footer/>
      </body>
    </html>
  );
}